import type { ApplicationVolunteerCard } from './application-status-types';

export const mockApplicationStatusCards: ApplicationVolunteerCard[] = [
  {
    id: 1,
    status: 'RECRUITING',
    title: '장애학우 수업 도우미 모집',
    credit: '봉사 인정 시간 : 회차당 3시간 인정',
    location: '샬롬관 807호',
    period: '2026.03.13 ~ 2026.06.19 (매주 금요일)',
    time: '11:30 ~ 16:30',
    recruitCount: 1,
    applicantCount: 3,
    favorite: true,
    applied: true,
    hasPreferredCondition: true,
    progressStep: 2,
  },
  {
    id: 2,
    status: 'RECRUITING',
    title: '[대플] 선배와 함께하는 취업 멘토링 프로그램 [강냉이 신입사원 만들기] 멘티 모집!',
    credit: '봉사 인정 시간 : 일 최대 4시간 인정',
    location: '대학일자리플러스센터 상담실',
    period: '2026.05.14 ~ 2026.05.16',
    time: '10:00 ~ 16:00',
    recruitCount: 10,
    applicantCount: 11,
    favorite: true,
    applied: false,
    hasPreferredCondition: false,
  },
  {
    id: 3,
    status: 'RECRUITING',
    title: '교내 환경 정리 봉사자 모집',
    credit: '봉사 인정 시간 : 회차당 2시간 인정',
    location: '학생회관 앞',
    period: '2026.07.03',
    time: '13:00 ~ 15:00',
    recruitCount: 5,
    applicantCount: 2,
    favorite: true,
    applied: false,
    hasPreferredCondition: false,
  },
  {
    id: 4,
    status: 'RECRUITING',
    title: '도서관 자료 정리 보조 모집',
    credit: '봉사 인정 시간 : 회차당 3시간 인정',
    location: '중앙도서관',
    period: '2026.07.10',
    time: '09:00 ~ 12:00',
    recruitCount: 4,
    applicantCount: 1,
    favorite: true,
    applied: false,
    hasPreferredCondition: true,
  },
];
